services:
- docker:dind

stages:
- test
- push

test:
  image: docker:dind
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - docker build . -f Dockerfile.dev --build-arg BASE_RUCIO_CLIENT_IMAGE=registry.gitlab.com/ska-telescope/src/ska-rucio-client --build-arg BASE_RUCIO_CLIENT_TAG=$(cat BASE_RUCIO_CLIENT_TAG) --tag registry.gitlab.com/ska-telescope/src/ska-rucio-extended-client:$(cat BASE_RUCIO_CLIENT_TAG)
    - docker run -t --rm registry.gitlab.com/ska-telescope/src/ska-rucio-extended-client:$(cat BASE_RUCIO_CLIENT_TAG) test/run_unittests.sh

push:
  image: docker:dind
  stage: push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  needs:
    - test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f Dockerfile --build-arg BASE_RUCIO_CLIENT_IMAGE=registry.gitlab.com/ska-telescope/src/ska-rucio-client --build-arg BASE_RUCIO_CLIENT_TAG=$(cat BASE_RUCIO_CLIENT_TAG) --tag registry.gitlab.com/ska-telescope/src/ska-rucio-extended-client:$(cat BASE_RUCIO_CLIENT_TAG)
    - docker push registry.gitlab.com/ska-telescope/src/ska-rucio-extended-client:$(cat BASE_RUCIO_CLIENT_TAG)
