services:
- docker:dind

stages:
- build
- test
- push

build:
  image: docker:dind
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f Dockerfile --build-arg BASE_RUCIO_CLIENT_IMAGE=registry.gitlab.com/ska-telescope/src/ska-rucio-client --build-arg BASE_RUCIO_CLIENT_TAG=$(cat BASE_RUCIO_CLIENT_TAG) --tag $CI_REGISTRY_IMAGE:$(cat BASE_RUCIO_CLIENT_TAG)
    - docker run -t --rm $CI_REGISTRY_IMAGE:$(cat BASE_RUCIO_CLIENT_TAG)

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$(cat BASE_RUCIO_CLIENT_TAG)
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs:
    - build
  script:
    - /opt/rucio-extended-client/test/run_unittests.sh

push:
  image: docker:dind
  stage: push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs:
    - build
    - test
  script:
    - docker push $CI_REGISTRY_IMAGE:$(cat BASE_RUCIO_CLIENT_TAG)
