ARG BASE_SKA_RUCIO_CLIENT_IMAGE
ARG BASE_SKA_RUCIO_CLIENT_TAG

FROM $BASE_SKA_RUCIO_CLIENT_IMAGE:$BASE_SKA_RUCIO_CLIENT_TAG

USER root

RUN yum -y install tree

COPY . /opt/ska-rucio-extended-client

RUN cd /opt/ska-rucio-extended-client && python3 -m pip install -e .

RUN ln -s /opt/ska-rucio-extended-client/etc/config.ini /usr/local/etc/config.ini

USER user

WORKDIR /opt/ska-rucio-extended-client

ENTRYPOINT ["/bin/bash"]
